### ISSUE TITLE
MockSlingExtensions.setRequestContext should accept SlingContextImpl instead of AemContextImpl

### ISSUE THREAD

**Issue by henrykuijpers** [wcm-io/io.wcm.testing.wcm-io-mock.sling#1]
When trying to call `MockSlingExtensions.setRequestContext(slingContext, slingContext.request())`, a compilation error is shown. The first parameter needs to be an `AemContextImpl` instead of a `SlingContextImpl`.

However, there is no reason this should be an `AemContextImpl`, as `SlingContextImpl` should suffice.

**Comment by stefanseifert** [comment]
this could be done together with https://github.com/wcm-io/io.wcm.testing.wcm-io-mock.sling/issues/2 (see comments there). without that change, i think it's of no help as you have to use AemContext anyway for the plugin?

**Comment by henrykuijpers** [comment]
Yes, I agree!
